name: Spawner
main: com.chrissquared.awesomepants.Spawner.Spawner
version: 0.3
website: http://bukkitfun.tumblr.com/
author: AwesomePants
description: Spawner plugin.
commands:
  spawn:
    description: >
                 Spawns one or more creatures, at a player (or location - not yet implemented).
                 Warning: Target player defaults to the calling player!
    usage: |
           Usage -
           /<command> [mob] [targetplayer] - Spawns a mob, near the player.
           /<command> creepergeddon [targetplayer] - Spawns a pack of creepers.
           /<command> undeadarmy [targetplayer] - Spawns a pack of creepers.
